# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3696649bc9116340d44eb05798d5760b02d81c8d6849e64383a8b4e4c9af90c3ce8c72984e3cd6e2ae60c698d6c3bd94a54af954d2f4c994edaea579b28b1eb9

test:
  secret_key_base: 943aa87dff134c44cfef033ec9e3b0907e64c74b7ac12708aa2eba1143e1943fb15b533f1485e7834a6182e0ba0bb9f16b1041186e29fe45410314bbbea05af8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
